### ISSUE TITLE
Gracefully handle an org having no public/accessible repos

### ISSUE THREAD

**Issue by rgmz** [boostsecurityio/poutine#100]
**Is your feature request related to a problem? Please describe.**
Presently, if you scan an org that has no public repositories, you will encounter a confusing error message.

```
8:12PM | ERROR | No repositories found for org $org
Error: failed to analyze org $org: failed to get batch of repos: no repositories found for org $org
Usage:
  poutine analyze_org [flags]

Flags:
  -h, --help           help for analyze_org
  -i, --ignore-forks   Ignore forked repositories in the organization
  -j, --threads int    Parallelization factor for scanning organizations (default 2)
  -t, --token string   SCM access token (env: GH_TOKEN)

Global Flags:
      --config string         config file (default is .poutine.yml in the current directory)
  -f, --format string         Output format (pretty, json, sarif) (default "pretty")
  -s, --scm string            SCM platform (github, gitlab) (default "github")
  -b, --scm-base-url string   Base URI of the self-hosted SCM instance (optional)
  -v, --verbose               Enable verbose logging

8:12PM | ERROR | error="failed to analyze org $org: failed to get batch of repos: no repositories found for org $org"
```

This is because the code returns an error if the repository count is 0.
https://github.com/boostsecurityio/poutine/blob/4416b90c629f8a1a283017c5f8019460f4a4d25a/providers/github/client.go#L274-L278

**Describe the solution you'd like**
Update the logic to differentiate between "the request failed" and "the org has no repositories".

**Describe alternatives you've considered**
N/A

**Additional context**
I'm happy to open a PR for this. Thoughts or suggestions are welcome.

**Comment by fproulx-boostsecurity** [comment]
Thanks @rgmz , yes PR is welcome.
