### ISSUE TITLE
Improve ADO : add System.Debug detection

### ISSUE THREAD

**Issue by fproulx-boostsecurity** [boostsecurityio/poutine#165]

**Comment by SUSTAPLE117** [comment]
https://learn.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#systemdebug

**Comment by fproulx-boostsecurity** [comment]
https://github.com/usnistgov/fipy/blob/3c7c8c1921b415a7d5a45f7a9b5a7c191514aa10/.azure/pipelines.yml#L22-L23
