### ISSUE TITLE
Include event triggers in results metadata

### ISSUE THREAD

**Issue by bthuilot** [boostsecurityio/poutine#232]
**Is your feature request related to a problem? Please describe.**

When going through results of a poutine scan (particularly with `injections`, `untrusted_checkout_exec` and `know_vulnerability_in_component`) I would like to know the event triggers for the workflow. Currently I have to open the file on the GitHub UI to check for each one. 

**Describe the solution you'd like**

I would like to request a `event_triggers` field included in the `metadata` object returned for relevant results (results that are for a particular workflow)

**Comment by fproulx-boostsecurity** [comment]
Thanks for your feature request. Should be pretty easy to add to the JSON output. 

@SUSTAPLE117 lets review tomorrow.

**Comment by fproulx-boostsecurity** [comment]
Closed by #233
