### ISSUE TITLE
Publish to Homebrew

### ISSUE THREAD

**Issue by fproulx-boostsecurity** [boostsecurityio/poutine#94]
Instead of using local brew tap, we should push to the upstream homebrew.

**Comment by richardtorres314** [comment]
@fproulx-boostsecurity Would it be okay if I took this on? I've written brew formulas before. Just to confirm, `poutine` will be the intended formula name, correct? Thank you!

**Comment by fproulx-boostsecurity** [comment]
@richardtorres314 that would be an amazing contribution. 
Yes, like call it `poutine`.
I think we'd like to keep publishing to our local tap as well.
How does it work to update in Homebrew itself, it is manual PR on their side or it's built-in to `goreleaser` ?

**Comment by richardtorres314** [comment]
@fproulx-boostsecurity Awesome! It would just be opening a PR in Homebrew's repo to add the formula to their list. No changes needed from poutine!

PS - Heard about this project from FLOSS Weekly. Great work!

**Comment by fproulx-boostsecurity** [comment]
@richardtorres314 alright, then you can go ahead. CC me on the PR
I'm guessing that will be here https://github.com/Homebrew/homebrew-core ?

**Comment by richardtorres314** [comment]
@fproulx-boostsecurity Yup, that's the repo

**Comment by fproulx-boostsecurity** [comment]
@richardtorres314 any updates ?

**Comment by richardtorres314** [comment]
@fproulx-boostsecurity I'm having troubles getting the build to succeed locally. I have a working branch [here](https://github.com/Homebrew/homebrew-core/compare/master...richardtorres314:homebrew-core:poutine-branch) if you'd like to take a look. Thank you!

**Comment by fproulx-boostsecurity** [comment]
Thanks @richardtorres314 , we'll have a look today

**Comment by fproulx-boostsecurity** [comment]
@richardtorres314 I think I got it https://github.com/Homebrew/homebrew-core/pull/174258
It's pending approval on their side 🤞
